language: c
compiler:
  - gcc
  - clang
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install colorgcc gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/colorgcc 50
  - sudo bash -c 'echo gccVersion":" 4.8 >> /etc/colorgcc/colorgccrc'
script: make CC=$CC all
